### PR TITLE
Improving VORP Fishing

### PR DESCRIPTION
**Pull request by cl3i550n**
# Pull request template
> [!IMPORTANT]
> Please complete all fields. PRs will not be merged if any fields are incomplete. Be respectful, and keep in mind that it may take some time for your PR to be reviewed.
>
> Bear in mind refactors are up to the developers and not it's contributors after all we are the ones giving support when needed. if they are big changes I suggest you to release it under your name instead.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [x] Improving

### Motive for This Pull Request
Old files and organization is so bad

- VIDEO show works fine - https://streamable.com/z5s9bb

### Explain the necessity of these changes and how they will impact the framework or its users.
Improving VORP Fishing
### Organization of Folders added
- Added server and client lua files inside folders
- Adjusted system of translation for default methods of others vorp scripts

### FxManifest
- Declarations of all files and dependencies added

### Code
- Using new exports of VORPcore and Inventory
- Added NotifyAdvanced after capture fish
- Added TextureFishing show in notify
- Webhook replaced to use of VORPcore and added DiscordFooterLogo
- Config.lua are more clean
- Created data files in config folder, separated

@outsider31000 

### Please describe the tests you have conducted to verify your changes. Provide instructions so we can reproduce these tests. Also, list any relevant details for your test configuration.

- [x] Tested with latest vorp scripts
- [x] Tested with latest artifacts

### CODE REVIEW

**Comment by outsider31000** [comment]
Hi

please read before making pull request.
image

explantion of the changes you made must be all in the fields of the template.

the fields say to **explain**  

`Old files and organization is so bad`
 this isnt an explantion 
neither this 

```Improving VORP Fishing

    Better organization files
    Translation
    And others
```

explain everything that was changed and why.

**Comment by cl3i550n** [comment]
## All ChangeLog

### Organization of Folders added
- Added server and client lua files inside folders
- Adjusted system of translation for default methods of others vorp scripts

### FxManifest
- Declarations of all files and dependencies added

### Code
- Using new exports of VORPcore and Inventory
- Added NotifyAdvanced after capture fish
- Added TextureFishing show in notify
- Webhook replaced to use of VORPcore and added DiscordFooterLogo
- Config.lua are more clean
- Created data files in config folder, separated

@outsider31000

**Comment by cl3i550n** [comment]
## Last commit

- Update to 1.2 fixmanifest and added changelog in "version" file.

**Comment by creativewild** [comment]
A note, this added no improvements, its just basically swapped things around, not sure what this was trying to accomplish, I need to do a full rework of the code itself so most of things with the exception of the language file which now follows the Vorp standart, will likely be reverted and some will be added directly to the code as they are constants, like the baits, they were left in the config at the time in case of new additions but thats not the case anymore

**Pull request merged**
